Update README.md
Docker does not allow to "move" file as part of the rename procedure.  For what ever reasons json-server needs to do it. 
It  throws exception:
/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/disk.js:14
      if (err) throw err
               ^
Error: EBUSY: resource busy or locked, rename '/data/.~db.json' -> '/data/db.json'
    at Error (native)

However when docker mounts directory from host to the container then any files within directory can be "moved".